- hosts: localhost
  gather_facts: no
  vars:
    shortcuts:
    - name: "shell"
      binding: "<Alt><Shift>s"
      command: "gnome-terminal"
    - name: "web"
      binding: "<Alt><Shift>w"
      command: "google-chrome"
    - name: "doer"
      binding: "<Alt><Shift>d"
      command: "doer"
    - name: "edd"
      binding: "<Alt><Shift>e"
      command: "evince"
  tasks:

  - name: Keyboard shortcut names
    dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ item.name }}/name"
      value: "'{{ item.name }}'"
      state: present
    with_items: "{{ shortcuts }}"

  - name: Keyboard shortcut bindings
    dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ item.name }}/binding"
      value: "'{{ item.binding }}'"
      state: present
    with_items: "{{ shortcuts }}"

  - name: Keyboard shortcut commands
    dconf:
      key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ item.name }}/command"
      value: "'{{ item.command }}'"
      state: present
    with_items: "{{ shortcuts }}"

  - name: List of custom key bindings
    dconf:
      key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings
      value: "[{% for shortcut in shortcuts %}'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ shortcut.name }}/'{% if not loop.last %}, {% endif %}{% endfor %}]"
      state: present
