- hosts: localhost
  gather_facts: no
  vars:
    workspaces: 7
    shortcuts:
    - workspace: 1
      binding: "<Alt><Shift>i"
    - workspace: 2
      binding: "<Alt><Shift>u"
    - workspace: 3
      binding: "<Alt><Shift>l"
    - workspace: 4
      binding: "<Alt><Shift>k"
    - workspace: 5
      binding: "<Alt><Shift>j"
    - workspace: 6
      binding: "<Alt><Shift>n"
    - workspace: 7
      binding: "<Alt><Shift>m"
  tasks:

  - name: Fixed number of workspaces
    dconf:
      key: /org/gnome/desktop/wm/preferences/num-workspaces
      value: "{{ workspaces }}"
      state: present

  - name: Keyboard shortcuts for switching workspaces
    dconf:
      key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-{{ item.workspace }}"
      value: "['<Alt><Shift>{{ item.binding }}']"
      state: present
    with_items: "{{ shortcuts }}"
