- name: Install system packages
  become: yes
  tags: system
  package:
    state: latest
    name:
    - vim
    - tree
    - meld
    - python-pip

- name: Keep the system updated
  become: yes
  package:
    name: '*'
    state: latest

- name: Install system packages (Debian)
  become: yes
  tags: system
  package:
    state: latest
    name:
    - gnome-tweaks
    - virtualenvwrapper
  when: ansible_os_family == "Debian"

- name: Install system packages (RedHat)
  become: yes
  tags: system
  package:
    state: latest
    name:
    - gnome-tweak-tool
    - python-virtualenvwrapper
  when: ansible_os_family == "RedHat"

- name: Install Python packages
  become: yes
  tags: system
  pip:
    state: present
    name:
    - psutil
