- name: Install system packages
  become: yes
  package:
    state: latest
    name:
    - vim
    - tree
    - python-pip
    - gnome-tweaks

- name: Install Python packages
  become: yes
  pip:
    state: present
    name:
    - psutil
