- name: Tools directory
  file:
    path: "{{ tools }}"
    state: directory

- name: Fetch github repositories
  git:
    repo: "git@github.com:psss/{{ item }}.git"
    dest: "{{ tools }}/{{ item }}"
    update: no
  with_items:
    - box
    - did
    - dot
    - edd
    - fmf
