- name: Tools directory
  file:
    path: "{{ home }}/git"
    state: directory

- name: Fetch github repositories
  git:
    repo: "git@github.com:psss/{{ item }}.git"
    dest: "{{ home }}/git/{{ item }}"
  with_items:
    - box
    - did
    - dot
    - edd
    - fmf
