- name: Tools directory
  file:
    path: "{{ home }}/git"
    state: directory

- name: Fetch git repositories
  git:
    repo: "{{ item.url }}"
    dest: "{{ home }}/git/{{ item.repo }}"
  with_items: "{{ repositories }}"

- name: Set git user email
  git_config:
    name: user.email
    value: "{{ item.email }}"
    repo: "{{ home }}/git/{{ item.repo }}"
    scope: "local"
  with_items: "{{ repositories }}"
  when: "item.email is defined"
