- name: Fixed number of workspaces
  dconf:
    key: /org/gnome/mutter/dynamic-workspaces
    value: "false"
    state: present

- name: Set the number of workspaces
  dconf:
    key: /org/gnome/desktop/wm/preferences/num-workspaces
    value: "{{ workspaces|length }}"
    state: present

- name: Keyboard shortcuts for switching workspaces
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-{{ item.workspace }}"
    value: "['{{ item.binding }}']"
    state: present
  with_items: "{{ workspaces }}"
